### ISSUE TITLE
EnableVectorAcceleration 问题

### ISSUE THREAD

**Issue by Hush-vv** [Ketuer/MAXSUN-MS-iCraft-Z790ITX-WIFI-hackintosh#1]
EnableVectorAcceleration
Type: plist boolean
Failsafe: false
Description: Enable AVX vector acceleration of SHA-512 and SHA-384 hashing algorithms.
Note: This option may cause issues on certain laptop firmwares, including Lenovo.

EnebleVectorAccel是给 OC设置固件密码加速密码验证的吧？

**Comment by Ketuer** [comment]
参考：https://apple.sqlsec.com/4-OC配置/4-8.html
无论这个是做啥的，13代默认不支持AVX512，会导致一系列问题，关闭后一切正常

**Comment by Hush-vv** [comment]
<img width="596" alt="QQ20230516-012157@2x" src="https://github.com/Ketuer/MAXSUN-MS-iCraft-Z790ITX-WIFI-hackintosh/assets/61744850/fcef1b8e-eef5-4ae2-a477-afb0bf02b739">
我更相信牛牛大佬

**Comment by Ketuer** [comment]
> <img alt="QQ20230516-012157@2x" width="596" src="https://user-images.githubusercontent.com/61744850/238423347-fcef1b8e-eef5-4ae2-a477-afb0bf02b739.png"> 我更相信牛牛大佬

可是我关闭之后确实解决问题了，如果你觉得这个说法不对，你可以给我一个你认为是正确的说法，这个问题该如何去解决，我毕竟不是专业玩黑苹果的，愿意洗耳恭听

**Comment by amber9527loc** [comment]
请问使用使用BCM94352Z（直接替换主板上的AX211网卡）有屏蔽针脚吗？我使用同款无线网卡后发现蓝牙正常，wifi无法开启

**Comment by amber9527loc** [comment]
> 请问使用BCM94352Z（直接替换主板上的AX211网卡）有屏蔽针脚吗？我使用同款无线网卡后发现蓝牙正常，wifi无法开启

并且type-c口连接在主板io的c口，连接速率还是显示为480mpbs，不是10Gbps

**Comment by Hush-vv** [comment]
检查type-c数据线是否支持10Gbps，支持的话，可以尝试我efi里的usb定制文件

**Comment by amber9527loc** [comment]
> 检查type-c数据线是否支持10Gbps，支持的话，可以尝试我efi里的usb定制文件

检查过了，使用三星t7移动硬盘的原装type-c数据线和t7移动硬盘，理论是10gbps的速度，实测只有不到40m/s
我在win下定制usb，以及使用您的efi里的usb定制文件，hackintool里都显示为480mbps，搞不清楚原因

**Comment by amber9527loc** [comment]
<img width="1585" alt="截屏2023-05-16 19 07 19" src="https://github.com/Ketuer/MAXSUN-MS-iCraft-Z790ITX-WIFI-hackintosh/assets/133760538/63288d85-23f5-4222-8b9c-6441c89b9897">
而且我把原装的wifi卡替换为博通卡后，竟然还显示有0✖️8086的intel设备，可能这是导致我无法正常开启wifi的原因，但我不知道怎么解决

**Comment by Ketuer** [comment]
> > 检查type-c数据线是否支持10Gbps，支持的话，可以尝试我efi里的usb定制文件
> 
> 检查过了，使用三星t7移动硬盘的原装type-c数据线和t7移动硬盘，理论是10gbps的速度，实测只有不到40m/s 我在win下定制usb，以及使用您的efi里的usb定制文件，hackintool里都显示为480mbps，搞不清楚原因

看看是不是连接的这个C口，如果不是可能是被识别错了，我移动硬盘可以5Gbps速度连接：
<img width="487" alt="image" src="https://github.com/Ketuer/MAXSUN-MS-iCraft-Z790ITX-WIFI-hackintosh/assets/63346302/3aaa57ab-56a0-4d8a-96d8-88646ac71a56">

**Comment by Hush-vv** [comment]
C口可以10Gbps
<img width="786" alt="QQ20230517-002848@2x" src="https://github.com/Ketuer/MAXSUN-MS-iCraft-Z790ITX-WIFI-hackintosh/assets/61744850/ec50956c-5e98-4dba-805b-225114dfb614">

**Comment by amber9527loc** [comment]
> C口可以10Gbps
> <img alt="QQ20230517-002848@2x" width="786" src="https://user-images.githubusercontent.com/61744850/238711461-ec50956c-5e98-4dba-805b-225114dfb614.png">

感谢！

**Comment by amber9527loc** [comment]
> C口可以10Gbps
> <img alt="QQ20230517-002848@2x" width="786" src="https://user-images.githubusercontent.com/61744850/238711461-ec50956c-5e98-4dba-805b-225114dfb614.png">

我插入c口发现接入的是HS05，我重新定制一下usb

**Comment by Hush-vv** [comment]
HSxx都是USB2.0。确定设备和线支持的话，插入usb的时候插快一些，插慢了就可能被识别成2.0
